const types = {
  //failed
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  //all product
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  //single product
  GET_DETAIL_PRODUCT_REQUEST: "GET_DETAIL_PRODUCT_REQUEST",
  GET_DETAIL_PRODUCT_SUCCESS: "GET_DETAIL_PRODUCT_SUCCESS",

  //all categoryProduct
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",

  //product per category
  GET_PRODUCT_CATEGORY_REQUEST: "GET_PRODUCT_CATEGORY_REQUEST",
  GET_PRODUCT_CATEGORY_SUCCESS: "GET_PRODUCT_CATEGORY_SUCCESS",
};

export default types;
