const types = {
  //failed
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  //all product
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  //single product
  GET_DETAIL_PRODUCT_REQUEST: "GET_DETAIL_PRODUCT_REQUEST",
  GET_DETAIL_PRODUCT_SUCCESS: "GET_DETAIL_PRODUCT_SUCCESS",
};

export default types;
